### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by dnknn** [jlawrence6809/CSS-Selector-Helper-for-Chrome#2]

**Comment by jlawrence6809** [comment]
Hello! Thanks for your interest!

1. Visibility is implemented to roughly match how Selenium webdriver does visibility checks.
https://www.w3.org/TR/webdriver/#element-displayedness

2. The numbers are meant to indicate which match is currently being highlighted on the page/dom. In your image it would be the 4th of 4 element matches on the page.

As far as settings. I need to go back and rewrite most of this. I wrote this as a side project in my first year as a SDET and knew basically nothing about ui design.

**Comment by dnknn** [comment]
> In your image it would be the 4th of 4 element matches on the page.
No, i know the meaning of numbers.
I mean that the eyes cannot be seen clearly because it is too dark, In other words, the color contrast is too low.

**Comment by dnknn** [comment]
🎀Summary without rewrite: 
❶ Add &ensp;<kbd>Ctrl+C</kbd>&ensp; for Copy👇
![0623080438](https://user-images.githubusercontent.com/10995302/85346495-32927600-b528-11ea-9a23-d8c36eb41529.png)

❷Strengthen visual Color-Contrast-ratio:
- Selected ⚔ Unselected.
- The number between Prev and Next.

![0623081539](https://user-images.githubusercontent.com/10995302/85346977-bc8f0e80-b529-11ea-9725-9e877f52e94e.png)


![image](https://user-images.githubusercontent.com/10995302/85347950-aa629f80-b52c-11ea-89ca-519e2e7d4738.png)

https://developers.google.com/web/updates/2019/01/devtools#AAA

**Comment by jlawrence6809** [comment]
@dnknn 
These are all really great suggestions. I am going to see about getting these in the next few weeks. Thank you for your input!

**Comment by dnknn** [comment]
@jlawrence6809  Thanks♪(･ω･)ﾉ

![0626054208](https://user-images.githubusercontent.com/10995302/85798288-ce61f300-b76f-11ea-8e8d-e423fa7241bb.png)

I don’t understand anything except CSS , I changed it to this with 🅲🆂🆂 . Haha

I hope to give priority:  Put `.class` in front of `[attribute]`

--Thanks again and good luck
