### ISSUE TITLE
Selector copying does not work if #copy exists on the page

### ISSUE THREAD

**Issue by IAkumaI** [jlawrence6809/CSS-Selector-Helper-for-Chrome#6]
Button "Selector to clipboard" does not work if there is element with id "copy" on the page. If remove this element manually, copying will works.

It's because of using window.copy method. Chrome thinks you call DOM element instead of real function.

**Comment by jjl-genemod** [comment]
I'll look into this tonight. Thanks!

**Comment by dnknn** [comment]
> If remove this `#id`  element manually, copying will works.

@IAkumaI 👍

demo: https://www.youtube.com/
![image](https://user-images.githubusercontent.com/10995302/116763936-dfdfef80-aa51-11eb-865b-c3ed708ae658.png)

**Comment by dnknn** [comment]
@jjl-genemod By the way, a suggestion:  can you adjust the sorting?


<img align=right width=50% src=https://user-images.githubusercontent.com/10995302/116767359-4e2cae00-aa62-11eb-9e3d-95f66ce5b6a0.png>

- ##  **Current sorting:** 
　　　👎 `#id` -> `[attr]` ->  `.class` -> `tag`

- ##  **Expected sorting:** 
　　　👍 `tag` -> `#id` -> `.class` -> `[attr]`

- Why?
> 1.  `tag` is a type identification,  and `tag` is short, usually 1-5 letters.
> 2. `#id` is unique.
> 3.  `.class`
> 4. `[attr]` may be multiple , and they may be very long.

**Comment by jlawrence6809** [comment]
Unfortunately I haven't ever found a way to get around that. It seems when the copy function is overridden then it is no longer usable. In the updated extension there will be a box you can select and copy from.

**Comment by jlawrence6809** [comment]
I'm closing this out as solved!
